# for local development only!
services:
  frontend:
    build:
      context: ./Project.App/Project.Client
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./Project.App/Project.Api
    environment:
      # binds to ConnectionStrings:DefaultConnection
      - ConnectionStrings__DefaultConnection=Server=db;Database=DevitoDB;User Id=SA;Password=ThisIsTheBestPassword!!1!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7069;http://+:5131
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devcertpass
    ports:
      - 5131:5131 # http
      - 7069:7069 # https
    depends_on:
      - db
    volumes:
      # dev certificate directory (assumes windows machine)
      # to create the certificate:
      # > `dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p devcertpass`
      # > `dotnet dev-certs https --trust`
      # see: https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-9.0
      - ${USERPROFILE}/.aspnet/https:/https/

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ThisIsTheBestPassword!!1!
      - MSSQL_PID=Developer # set to developer cuz we're developing :)
      - MSSQL_DATABASE=DevitoDB
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: # persist database data
